FROM php:8.2-apache


RUN docker-php-ext-install mysqli pdo pdo_mysql


RUN a2enmod rewrite


WORKDIR /var/www/html


RUN mkdir -p /var/www/html/api /var/www/html/includes


RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html


CMD ["apache2-foreground"]
